[package]
name = "cnx-bin"
version = "0.1.0"
authors = ["Michael <3533648+hertg@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cnx = "0.3.0"
anyhow = "1.0.41"